#服务器端口
server:
  port: 8888

#lombok的日志处理
logging:
  path: logs
  file: mylog.log


spring:
  application:
    name: myTest

  #数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store
    password: root
    username: root


mybatis:
  type-aliases-package: com.course.model  #java bean
  mapper-locations:
    - mapper/*    #mysql.xml文件映射到这
